theme: minima
title: My First Blog Entry
author: allex-kirkland
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  New Blog entry to better help with GitHub learning. This is being used in order to create a person GitHub folder to house documents, projects and other items.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
